# Site settings
title: NDSU ACM
email: acm@ndacm.org
url: http://ndacm.org
description: "The student chapter of the Association for Computing Machinery was established the North Dakota State University in 1974. Since them the organization has been involved with providing sevices, organizing programming competitions, and offering education and social opportunites for its members. While most of the members are Computer Science students, the ACM also welcomes people in other fields who are interested in technology. Thus our chapter also has students in Mathematics, Engineering, Psychology, and other Sciences."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#45693C'
  links: '#fff'

# Footer settings
footer: NDSU Association for Computing Machinery

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/acm-ndsu

# Build settings
markdown: kramdown
permalink: pretty

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "posts"
    -
        scope:
            path: "corp-talks"
            type: "pages"
        values:
            layout: "pages"
    -
        scope:
            path: "cabinet"
            type: "pages"
        values:
            layout: "pages"
    -
        scope:
            path: "constitution"
            type: "pages"
        values:
            layout: "pages"
    -
        scope:
            path: "sigs"
            type: "pages"
        values:
            layout: "pages"
    -
        scope:
            path: "weekly-meetings"
            type: "pages"
        values:
            layout: "pages"
    -
        scope:
            path: "meeting-minutes"
            type: "pages"
        values:
            layout: "pages"

exclude: [vendor]
include: [".htaccess"]
destination: _deploy

